export const category = [
  {
    cinsiyet: "Cinsiyet",
    tarz: [
      { name: "Business Casual" },
      { name: "Retro" },
      { name: "Vintage" },
      { name: "Basic" },
      { name: "Old Money" },
      { name: "Street" },
    ],
    ust: [
      { name: "Gömlek" },
      { name: "Tişört" },
      { name: "Sweatshirt" },
      { name: "Crop" },
      { name: "Bluz" },
      { name: "Elbise" },
    ],
    alt: [
      { name: "Pantolon" },
      { name: "Eşofman" },
      { name: "Şort" },
      { name: "Tayt" },
      { name: "Etek" },
    ],
    ustRenk: [
      { name: "Kırmızı" },
      { name: "Beyaz" },
      { name: "Sarı" },
      { name: "Yeşil" },
      { name: "Mavi" },
      { name: "Mor" },
      { name: "Gri" },
    ],
    altRenk: [
      { name: "Kırmızı" },
      { name: "Beyaz" },
      { name: "Sarı" },
      { name: "Yeşil" },
      { name: "Mavi" },
      { name: "Mor" },
      { name: "Gri" },
    ],
  },
  {
    cinsiyet: "Erkek",
    tarz: [
      { name: "Business Casual" },
      { name: "Retro" },
      { name: "Vintage" },
      { name: "Basic" },
      { name: "Old Money" },
      { name: "Street" },
    ],
    ust: [{ name: "Gömlek" }, { name: "Tişört" }, { name: "Sweatshirt" }],
    alt: [{ name: "Pantolon" }, { name: "Eşofman" }, { name: "Şort" }],
    ustRenk: [
      { name: "kırmızı" },
      { name: "beyaz" },
      { name: "sarı" },
      { name: "yeşil" },
      { name: "mavi" },
      { name: "mor" },
      { name: "gri" },
    ],
    altRenk: [
      { name: "kırmızı" },
      { name: "beyaz" },
      { name: "sarı" },
      { name: "yeşil" },
      { name: "mavi" },
      { name: "mor" },
      { name: "gri" },
    ],
  },
  {
    cinsiyet: "Kadın",
    tarz: [
      { name: "Classic" },
      { name: "Retro" },
      { name: "Vintage" },
      { name: "Urban" },
      { name: "Feminen" },
      { name: "Tesettür" },
    ],
    ust: [
      { name: "Crop" },
      { name: "Bluz" },
      { name: "Gömlek" },
      { name: "Tişört" },
      { name: "Sweatshirt" },
      { name: "Elbise" },
    ],
    alt: [
      { name: "Pantolon" },
      { name: "Tayt" },
      { name: "Şort" },
      { name: "Etek" },
    ],
    ustRenk: [
      { name: "kırmızı" },
      { name: "beyaz" },
      { name: "sarı" },
      { name: "yeşil" },
      { name: "mavi" },
      { name: "mor" },
      { name: "gri" },
    ],
    altRenk: [
      { name: "kırmızı" },
      { name: "beyaz" },
      { name: "sarı" },
      { name: "yeşil" },
      { name: "mavi" },
      { name: "mor" },
      { name: "gri" },
    ],
  },
];
